package main

import (
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"

	"github.com/wowsims/wotlk/sim/core/stats"
)

func statsLiteral(s stats.Stats) string {
	var parts []string
	for i, v := range s {
		if v != 0 {
			parts = append(parts, fmt.Sprintf("stats.%s: %s", stats.Stat(i).StatName(), strconv.FormatFloat(v, 'f', -1, 64)))
		}
	}
	return "stats.Stats{" + strings.Join(parts, ", ") + "}"
}

func durationLiteral(ms int32) string {
	switch {
	case ms == 0:
		return "0"
	case ms%1000 == 0:
		return fmt.Sprintf("%d * time.Second", ms/1000)
	default:
		return fmt.Sprintf("%d * time.Millisecond", ms)
	}
}

func writeGenerated(path string, statements []string) error {
	var b strings.Builder
	b.WriteString("// Code generated by tools/cc/extract. DO NOT EDIT.\n// Regenerate with: ./build.ps1 cc\n\npackage cc\n\n")
	body := strings.Join(statements, "\n")
	var imports []string
	if strings.Contains(body, "time.") {
		imports = append(imports, `"time"`)
	}
	if strings.Contains(body, "stats.") {
		if len(imports) > 0 {
			imports = append(imports, "") // separate std and module imports
		}
		imports = append(imports, `"github.com/wowsims/wotlk/sim/core/stats"`)
	}
	if len(imports) > 0 {
		b.WriteString("import (\n" + strings.Join(imports, "\n") + "\n)\n\n")
	}
	b.WriteString("func init() {\n" + body + "\n}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("formatting generated code: %w\n%s", err, b.String())
	}
	return os.WriteFile(path, src, 0666)
}
