package database

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/wowsims/wotlk/sim/core/proto"
	"github.com/wowsims/wotlk/tools"
)

// CustomContent is the output of tools/cc/extract (assets/db_inputs/cc/), merged into the DB by gen_db.
type CustomContent struct {
	dir            string
	Custom         *WowDatabase
	StockOverrides *WowDatabase
	ServerItemIDs  map[int32]bool // nil = no restriction
	ApplyStock     bool
}

// LoadCustomContent returns nil when no custom content has been imported.
func LoadCustomContent(inputsDir string) *CustomContent {
	dir := filepath.Join(inputsDir, "cc")
	if _, err := os.Stat(filepath.Join(dir, "cc_db.json")); err != nil {
		return nil
	}
	cc := &CustomContent{
		dir:            dir,
		Custom:         ReadDatabaseFromJson(tools.ReadFile(filepath.Join(dir, "cc_db.json"))),
		StockOverrides: NewWowDatabase(),
		ApplyStock:     true,
	}
	if _, err := os.Stat(filepath.Join(dir, "stock_overrides.json")); err == nil {
		cc.StockOverrides = ReadDatabaseFromJson(tools.ReadFile(filepath.Join(dir, "stock_overrides.json")))
	}
	var settings struct {
		ApplyStockItemChanges *bool `json:"applyStockItemChanges"`
	}
	if data, err := os.ReadFile(filepath.Join(dir, "settings.json")); err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			panic(fmt.Sprintf("cc/settings.json: %v", err))
		}
		if settings.ApplyStockItemChanges != nil {
			cc.ApplyStock = *settings.ApplyStockItemChanges
		}
	}
	if data, err := os.ReadFile(filepath.Join(dir, "server_item_ids.json")); err == nil {
		var ids []int32
		if err := json.Unmarshal(data, &ids); err != nil {
			panic(fmt.Sprintf("cc/server_item_ids.json: %v", err))
		}
		cc.ServerItemIDs = make(map[int32]bool, len(ids))
		for _, id := range ids {
			cc.ServerItemIDs[id] = true
		}
	}

	// Server naming conventions for unobtainable items (renamed stubs); stock items take server names.
	DenyListNameRegexes = append(DenyListNameRegexes,
		regexp.MustCompile(`^Obsolete`), regexp.MustCompile(`^NPC Equip `), regexp.MustCompile(`^QR \d`))

	// Custom content is always simmable and never deny-listed (servers often reuse unused item IDs).
	for id := range cc.Custom.Items {
		ItemAllowList[id] = struct{}{}
		delete(ItemDenyList, id)
	}
	for id := range cc.Custom.Gems {
		GemAllowList[id] = struct{}{}
		delete(GemDenyList, id)
	}
	return cc
}

// Apply merges custom content into db, applies server values to stock items and hides items
// that don't exist on the server. A summary of stock changes is written to cc/STOCK_CHANGES.md.
func (cc *CustomContent) Apply(db *WowDatabase) {
	var changes []string

	if cc.ApplyStock {
		for id, src := range cc.StockOverrides.Items {
			dst, ok := db.Items[id]
			if !ok {
				continue
			}
			if diff := diffItem(dst, src); len(diff) > 0 {
				changes = append(changes, fmt.Sprintf("| %d | %s | %s |", id, dst.Name, strings.Join(diff, "<br>")))
				dst.Stats = src.Stats
				dst.GemSockets = src.GemSockets
				dst.SocketBonus = src.SocketBonus
				dst.WeaponDamageMin, dst.WeaponDamageMax, dst.WeaponSpeed = src.WeaponDamageMin, src.WeaponDamageMax, src.WeaponSpeed
				dst.Ilvl = src.Ilvl
				dst.Quality = src.Quality
				dst.Name = src.Name
			}
		}
		for id, src := range cc.StockOverrides.Gems {
			dst, ok := db.Gems[id]
			if !ok {
				continue
			}
			if d := diffStats(dst.Stats, src.Stats); d != "" {
				changes = append(changes, fmt.Sprintf("| %d | %s (gem) | %s |", id, dst.Name, d))
				dst.Stats = src.Stats
				dst.Color = src.Color
			}
		}
	}

	removed := 0
	if cc.ServerItemIDs != nil {
		for id := range db.Items {
			if _, custom := cc.Custom.Items[id]; !custom && !cc.ServerItemIDs[id] {
				delete(db.Items, id)
				removed++
			}
		}
		for id := range db.Gems {
			if _, custom := cc.Custom.Gems[id]; !custom && !cc.ServerItemIDs[id] {
				delete(db.Gems, id)
				removed++
			}
		}
	}

	// Custom content replaces anything with the same ID.
	for id, item := range cc.Custom.Items {
		db.Items[id] = item
		if item.Icon != "" {
			db.ItemIcons[id] = &proto.IconData{Id: id, Name: item.Name, Icon: item.Icon}
		}
	}
	for id, gem := range cc.Custom.Gems {
		db.Gems[id] = gem
		if gem.Icon != "" {
			db.ItemIcons[id] = &proto.IconData{Id: id, Name: gem.Name, Icon: gem.Icon}
		}
	}
	for key, ench := range cc.Custom.Enchants {
		db.Enchants[key] = ench
		if ench.SpellId != 0 && ench.Icon != "" {
			db.SpellIcons[ench.SpellId] = &proto.IconData{Id: ench.SpellId, Name: ench.Name, Icon: ench.Icon}
		}
		if ench.ItemId != 0 && ench.Icon != "" {
			db.ItemIcons[ench.ItemId] = &proto.IconData{Id: ench.ItemId, Name: ench.Name, Icon: ench.Icon}
		}
	}

	sort.Strings(changes)
	var b strings.Builder
	b.WriteString("# Stock items changed by server data\n\nGenerated by gen_db from `stock_overrides.json`.\n\n")
	fmt.Fprintf(&b, "- Custom items/gems/enchants merged: %d / %d / %d\n", len(cc.Custom.Items), len(cc.Custom.Gems), len(cc.Custom.Enchants))
	fmt.Fprintf(&b, "- Stock items/gems not on the server (hidden): %d\n", removed)
	if !cc.ApplyStock {
		b.WriteString("- Stock item changes are disabled (`applyStockItemChanges: false` in cc_data/cc.json).\n")
	}
	fmt.Fprintf(&b, "- Stock items/gems whose values changed: %d\n\n", len(changes))
	if len(changes) > 0 {
		b.WriteString("| ID | Item | Change (wowhead -> server) |\n|---|---|---|\n")
		b.WriteString(strings.Join(changes, "\n") + "\n")
	}
	tools.WriteFile(filepath.Join(cc.dir, "STOCK_CHANGES.md"), b.String())
	fmt.Printf("cc: merged %d custom items, %d gems, %d enchants; %d stock changes; %d stock entries hidden\n",
		len(cc.Custom.Items), len(cc.Custom.Gems), len(cc.Custom.Enchants), len(changes), removed)
}

func diffItem(a, b *proto.UIItem) []string {
	var out []string
	if a.Name != b.Name {
		out = append(out, fmt.Sprintf("name %q -> %q", a.Name, b.Name))
	}
	if d := diffStats(a.Stats, b.Stats); d != "" {
		out = append(out, d)
	}
	if d := diffStats(a.SocketBonus, b.SocketBonus); d != "" {
		out = append(out, "socket bonus "+d)
	}
	if !slices.Equal(a.GemSockets, b.GemSockets) {
		out = append(out, fmt.Sprintf("sockets %v -> %v", a.GemSockets, b.GemSockets))
	}
	if a.WeaponDamageMin != b.WeaponDamageMin || a.WeaponDamageMax != b.WeaponDamageMax || a.WeaponSpeed != b.WeaponSpeed {
		out = append(out, fmt.Sprintf("weapon %.0f-%.0f/%.2f -> %.0f-%.0f/%.2f", a.WeaponDamageMin, a.WeaponDamageMax, a.WeaponSpeed,
			b.WeaponDamageMin, b.WeaponDamageMax, b.WeaponSpeed))
	}
	if a.Ilvl != b.Ilvl {
		out = append(out, fmt.Sprintf("ilvl %d -> %d", a.Ilvl, b.Ilvl))
	}
	if a.Quality != b.Quality {
		out = append(out, fmt.Sprintf("quality %s -> %s", a.Quality, b.Quality))
	}
	return out
}

func diffStats(a, b []float64) string {
	n := max(len(a), len(b))
	var parts []string
	for i := 0; i < n; i++ {
		var x, y float64
		if i < len(a) {
			x = a[i]
		}
		if i < len(b) {
			y = b[i]
		}
		if math.Abs(x-y) > 0.5 {
			parts = append(parts, fmt.Sprintf("%s %g -> %g", strings.TrimPrefix(proto.Stat(i).String(), "Stat"), x, y))
		}
	}
	return strings.Join(parts, ", ")
}
