package dbc

import "strings"

// Spell effect and aura names for 3.3.5a (TrinityCore SharedDefines.h / SpellAuraDefines.h).

var effectNames = strings.Split(`NONE INSTAKILL SCHOOL_DAMAGE DUMMY PORTAL_TELEPORT TELEPORT_UNITS APPLY_AURA ENVIRONMENTAL_DAMAGE `+
	`POWER_DRAIN HEALTH_LEECH HEAL BIND PORTAL RITUAL_BASE RITUAL_SPECIALIZE RITUAL_ACTIVATE_PORTAL QUEST_COMPLETE `+
	`WEAPON_DAMAGE_NOSCHOOL RESURRECT ADD_EXTRA_ATTACKS DODGE EVADE PARRY BLOCK CREATE_ITEM WEAPON DEFENSE `+
	`PERSISTENT_AREA_AURA SUMMON LEAP ENERGIZE WEAPON_PERCENT_DAMAGE TRIGGER_MISSILE OPEN_LOCK SUMMON_CHANGE_ITEM `+
	`APPLY_AREA_AURA_PARTY LEARN_SPELL SPELL_DEFENSE DISPEL LANGUAGE DUAL_WIELD JUMP JUMP_DEST `+
	`TELEPORT_UNITS_FACE_CASTER SKILL_STEP ADD_HONOR SPAWN TRADE_SKILL STEALTH DETECT TRANS_DOOR FORCE_CRITICAL_HIT `+
	`GUARANTEE_HIT ENCHANT_ITEM ENCHANT_ITEM_TEMPORARY TAMECREATURE SUMMON_PET LEARN_PET_SPELL WEAPON_DAMAGE `+
	`CREATE_RANDOM_ITEM PROFICIENCY SEND_EVENT POWER_BURN THREAT TRIGGER_SPELL APPLY_AREA_AURA_RAID CREATE_MANA_GEM `+
	`HEAL_MAX_HEALTH INTERRUPT_CAST DISTRACT PULL PICKPOCKET ADD_FARSIGHT UNTRAIN_TALENTS APPLY_GLYPH HEAL_MECHANICAL `+
	`SUMMON_OBJECT_WILD SCRIPT_EFFECT ATTACK SANCTUARY ADD_COMBO_POINTS CREATE_HOUSE BIND_SIGHT DUEL STUCK `+
	`SUMMON_PLAYER ACTIVATE_OBJECT GAMEOBJECT_DAMAGE GAMEOBJECT_REPAIR GAMEOBJECT_SET_DESTRUCTION_STATE KILL_CREDIT `+
	`THREAT_ALL ENCHANT_HELD_ITEM FORCE_DESELECT SELF_RESURRECT SKINNING CHARGE CAST_BUTTON KNOCK_BACK DISENCHANT `+
	`INEBRIATE FEED_PET DISMISS_PET REPUTATION SUMMON_OBJECT_SLOT1 SUMMON_OBJECT_SLOT2 SUMMON_OBJECT_SLOT3 `+
	`SUMMON_OBJECT_SLOT4 DISPEL_MECHANIC RESURRECT_PET DESTROY_ALL_TOTEMS DURABILITY_DAMAGE 112 RESURRECT_NEW `+
	`ATTACK_ME DURABILITY_DAMAGE_PCT SKIN_PLAYER_CORPSE SPIRIT_HEAL SKILL APPLY_AREA_AURA_PET TELEPORT_GRAVEYARD `+
	`NORMALIZED_WEAPON_DMG 122 SEND_TAXI PULL_TOWARDS MODIFY_THREAT_PERCENT STEAL_BENEFICIAL_BUFF PROSPECTING `+
	`APPLY_AREA_AURA_FRIEND APPLY_AREA_AURA_ENEMY REDIRECT_THREAT PLAY_SOUND PLAY_MUSIC UNLEARN_SPECIALIZATION `+
	`KILL_CREDIT2 CALL_PET HEAL_PCT ENERGIZE_PCT LEAP_BACK CLEAR_QUEST FORCE_CAST FORCE_CAST_WITH_VALUE `+
	`TRIGGER_SPELL_WITH_VALUE APPLY_AREA_AURA_OWNER KNOCK_BACK_DEST PULL_TOWARDS_DEST ACTIVATE_RUNE QUEST_FAIL `+
	`TRIGGER_MISSILE_SPELL_WITH_VALUE CHARGE_DEST QUEST_START TRIGGER_SPELL_2 SUMMON_RAF_FRIEND CREATE_TAMED_PET `+
	`DISCOVER_TAXI TITAN_GRIP ENCHANT_ITEM_PRISMATIC CREATE_ITEM_2 MILLING ALLOW_RENAME_PET FORCE_CAST_2 `+
	`TALENT_SPEC_COUNT TALENT_SPEC_SELECT 163 REMOVE_AURA`, " ")

var auraNames = strings.Split(`NONE BIND_SIGHT MOD_POSSESS PERIODIC_DAMAGE DUMMY MOD_CONFUSE MOD_CHARM MOD_FEAR PERIODIC_HEAL `+
	`MOD_ATTACKSPEED MOD_THREAT MOD_TAUNT MOD_STUN MOD_DAMAGE_DONE MOD_DAMAGE_TAKEN DAMAGE_SHIELD MOD_STEALTH `+
	`MOD_STEALTH_DETECT MOD_INVISIBILITY MOD_INVISIBILITY_DETECT OBS_MOD_HEALTH OBS_MOD_POWER MOD_RESISTANCE `+
	`PERIODIC_TRIGGER_SPELL PERIODIC_ENERGIZE MOD_PACIFY MOD_ROOT MOD_SILENCE REFLECT_SPELLS MOD_STAT MOD_SKILL `+
	`MOD_INCREASE_SPEED MOD_INCREASE_MOUNTED_SPEED MOD_DECREASE_SPEED MOD_INCREASE_HEALTH MOD_INCREASE_ENERGY `+
	`MOD_SHAPESHIFT EFFECT_IMMUNITY STATE_IMMUNITY SCHOOL_IMMUNITY DAMAGE_IMMUNITY DISPEL_IMMUNITY `+
	`PROC_TRIGGER_SPELL PROC_TRIGGER_DAMAGE TRACK_CREATURES TRACK_RESOURCES 46 MOD_PARRY_PERCENT 48 `+
	`MOD_DODGE_PERCENT MOD_CRITICAL_HEALING_AMOUNT MOD_BLOCK_PERCENT MOD_WEAPON_CRIT_PERCENT PERIODIC_LEECH `+
	`MOD_HIT_CHANCE MOD_SPELL_HIT_CHANCE TRANSFORM MOD_SPELL_CRIT_CHANCE MOD_INCREASE_SWIM_SPEED `+
	`MOD_DAMAGE_DONE_CREATURE MOD_PACIFY_SILENCE MOD_SCALE PERIODIC_HEALTH_FUNNEL 63 PERIODIC_MANA_LEECH `+
	`MOD_CASTING_SPEED_NOT_STACK FEIGN_DEATH MOD_DISARM MOD_STALKED SCHOOL_ABSORB EXTRA_ATTACKS `+
	`MOD_SPELL_CRIT_CHANCE_SCHOOL MOD_POWER_COST_SCHOOL_PCT MOD_POWER_COST_SCHOOL REFLECT_SPELLS_SCHOOL `+
	`MOD_LANGUAGE FAR_SIGHT MECHANIC_IMMUNITY MOUNTED MOD_DAMAGE_PERCENT_DONE MOD_PERCENT_STAT SPLIT_DAMAGE_PCT `+
	`WATER_BREATHING MOD_BASE_RESISTANCE MOD_REGEN MOD_POWER_REGEN CHANNEL_DEATH_ITEM MOD_DAMAGE_PERCENT_TAKEN `+
	`MOD_HEALTH_REGEN_PERCENT PERIODIC_DAMAGE_PERCENT 90 MOD_DETECT_RANGE PREVENTS_FLEEING MOD_UNATTACKABLE `+
	`INTERRUPT_REGEN GHOST SPELL_MAGNET MANA_SHIELD MOD_SKILL_TALENT MOD_ATTACK_POWER AURAS_VISIBLE `+
	`MOD_RESISTANCE_PCT MOD_MELEE_ATTACK_POWER_VERSUS MOD_TOTAL_THREAT WATER_WALK FEATHER_FALL HOVER `+
	`ADD_FLAT_MODIFIER ADD_PCT_MODIFIER ADD_TARGET_TRIGGER MOD_POWER_REGEN_PERCENT ADD_CASTER_HIT_TRIGGER `+
	`OVERRIDE_CLASS_SCRIPTS MOD_RANGED_DAMAGE_TAKEN MOD_RANGED_DAMAGE_TAKEN_PCT MOD_HEALING MOD_REGEN_DURING_COMBAT `+
	`MOD_MECHANIC_RESISTANCE MOD_HEALING_PCT 119 UNTRACKABLE EMPATHY MOD_OFFHAND_DAMAGE_PCT MOD_TARGET_RESISTANCE `+
	`MOD_RANGED_ATTACK_POWER MOD_MELEE_DAMAGE_TAKEN MOD_MELEE_DAMAGE_TAKEN_PCT RANGED_ATTACK_POWER_ATTACKER_BONUS `+
	`MOD_POSSESS_PET MOD_SPEED_ALWAYS MOD_MOUNTED_SPEED_ALWAYS MOD_RANGED_ATTACK_POWER_VERSUS `+
	`MOD_INCREASE_ENERGY_PERCENT MOD_INCREASE_HEALTH_PERCENT MOD_MANA_REGEN_INTERRUPT MOD_HEALING_DONE `+
	`MOD_HEALING_DONE_PERCENT MOD_TOTAL_STAT_PERCENTAGE MOD_MELEE_HASTE FORCE_REACTION MOD_RANGED_HASTE `+
	`MOD_RANGED_AMMO_HASTE MOD_BASE_RESISTANCE_PCT MOD_RESISTANCE_EXCLUSIVE SAFE_FALL MOD_PET_TALENT_POINTS `+
	`ALLOW_TAME_PET_TYPE MECHANIC_IMMUNITY_MASK RETAIN_COMBO_POINTS REDUCE_PUSHBACK MOD_SHIELD_BLOCKVALUE_PCT `+
	`TRACK_STEALTHED MOD_DETECTED_RANGE SPLIT_DAMAGE_FLAT MOD_STEALTH_LEVEL MOD_WATER_BREATHING `+
	`MOD_REPUTATION_GAIN PET_DAMAGE_MULTI MOD_SHIELD_BLOCKVALUE NO_PVP_CREDIT MOD_AOE_AVOIDANCE `+
	`MOD_HEALTH_REGEN_IN_COMBAT POWER_BURN MOD_CRIT_DAMAGE_BONUS 164 MELEE_ATTACK_POWER_ATTACKER_BONUS `+
	`MOD_ATTACK_POWER_PCT MOD_RANGED_ATTACK_POWER_PCT MOD_DAMAGE_DONE_VERSUS MOD_CRIT_PERCENT_VERSUS DETECT_AMORE `+
	`MOD_SPEED_NOT_STACK MOD_MOUNTED_SPEED_NOT_STACK 173 MOD_SPELL_DAMAGE_OF_STAT_PERCENT `+
	`MOD_SPELL_HEALING_OF_STAT_PERCENT SPIRIT_OF_REDEMPTION AOE_CHARM MOD_DEBUFF_RESISTANCE `+
	`MOD_ATTACKER_SPELL_CRIT_CHANCE MOD_FLAT_SPELL_DAMAGE_VERSUS 181 MOD_RESISTANCE_OF_STAT_PERCENT `+
	`MOD_CRITICAL_THREAT MOD_ATTACKER_MELEE_HIT_CHANCE MOD_ATTACKER_RANGED_HIT_CHANCE MOD_ATTACKER_SPELL_HIT_CHANCE `+
	`MOD_ATTACKER_MELEE_CRIT_CHANCE MOD_ATTACKER_RANGED_CRIT_CHANCE MOD_RATING MOD_FACTION_REPUTATION_GAIN `+
	`USE_NORMAL_MOVEMENT_SPEED MOD_MELEE_RANGED_HASTE MELEE_SLOW MOD_TARGET_ABSORB_SCHOOL `+
	`MOD_TARGET_ABILITY_ABSORB_SCHOOL MOD_COOLDOWN MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE 198 `+
	`MOD_INCREASES_SPELL_PCT_TO_HIT MOD_XP_PCT FLY IGNORE_COMBAT_RESULT MOD_ATTACKER_MELEE_CRIT_DAMAGE `+
	`MOD_ATTACKER_RANGED_CRIT_DAMAGE MOD_SCHOOL_CRIT_DMG_TAKEN MOD_INCREASE_VEHICLE_FLIGHT_SPEED `+
	`MOD_INCREASE_MOUNTED_FLIGHT_SPEED MOD_INCREASE_FLIGHT_SPEED MOD_MOUNTED_FLIGHT_SPEED_ALWAYS `+
	`MOD_VEHICLE_SPEED_ALWAYS MOD_FLIGHT_SPEED_NOT_STACK MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT `+
	`MOD_RAGE_FROM_DAMAGE_DEALT 214 ARENA_PREPARATION HASTE_SPELLS MOD_MELEE_HASTE_2 HASTE_RANGED `+
	`MOD_MANA_REGEN_FROM_STAT MOD_RATING_FROM_STAT MOD_DETAUNT 222 RAID_PROC_FROM_CHARGE 224 `+
	`RAID_PROC_FROM_CHARGE_WITH_VALUE PERIODIC_DUMMY PERIODIC_TRIGGER_SPELL_WITH_VALUE DETECT_STEALTH `+
	`MOD_AOE_DAMAGE_AVOIDANCE 230 PROC_TRIGGER_SPELL_WITH_VALUE MECHANIC_DURATION_MOD `+
	`CHANGE_MODEL_FOR_ALL_HUMANOIDS MECHANIC_DURATION_MOD_NOT_STACK MOD_DISPEL_RESIST CONTROL_VEHICLE `+
	`MOD_SPELL_DAMAGE_OF_ATTACK_POWER MOD_SPELL_HEALING_OF_ATTACK_POWER MOD_SCALE_2 MOD_EXPERTISE `+
	`FORCE_MOVE_FORWARD MOD_SPELL_DAMAGE_FROM_HEALING MOD_FACTION COMPREHEND_LANGUAGE MOD_AURA_DURATION_BY_DISPEL `+
	`MOD_AURA_DURATION_BY_DISPEL_NOT_STACK CLONE_CASTER MOD_COMBAT_RESULT_CHANCE CONVERT_RUNE MOD_INCREASE_HEALTH_2 `+
	`MOD_ENEMY_DODGE MOD_SPEED_SLOW_ALL MOD_BLOCK_CRIT_CHANCE MOD_DISARM_OFFHAND MOD_MECHANIC_DAMAGE_TAKEN_PERCENT `+
	`NO_REAGENT_USE MOD_TARGET_RESIST_BY_SPELL_CLASS 258 MOD_HOT_PCT SCREEN_EFFECT PHASE ABILITY_IGNORE_AURASTATE `+
	`ALLOW_ONLY_ABILITY 264 265 266 MOD_IMMUNE_AURA_APPLY_SCHOOL MOD_ATTACK_POWER_OF_STAT_PERCENT `+
	`MOD_IGNORE_TARGET_RESIST MOD_ABILITY_IGNORE_TARGET_RESIST MOD_DAMAGE_FROM_CASTER IGNORE_MELEE_RESET X_RAY `+
	`ABILITY_CONSUME_NO_AMMO MOD_IGNORE_SHAPESHIFT MOD_DAMAGE_DONE_FOR_MECHANIC MOD_MAX_AFFECTED_TARGETS `+
	`MOD_DISARM_RANGED INITIALIZE_IMAGES MOD_ARMOR_PENETRATION_PCT MOD_HONOR_GAIN_PCT MOD_BASE_HEALTH_PCT `+
	`MOD_HEALING_RECEIVED LINKED MOD_ATTACK_POWER_OF_ARMOR ABILITY_PERIODIC_CRIT DEFLECT_SPELLS `+
	`IGNORE_HIT_DIRECTION 289 MOD_CRIT_PCT MOD_XP_QUEST_PCT OPEN_STABLE OVERRIDE_SPELLS PREVENT_REGENERATE_POWER `+
	`295 SET_VEHICLE_ID BLOCK_SPELL_FAMILY STRANGULATE 299 SHARE_DAMAGE_PCT SCHOOL_HEAL_ABSORB 302 `+
	`MOD_DAMAGE_DONE_VERSUS_AURASTATE MOD_FAKE_INEBRIATE MOD_MINIMUM_SPEED 306 HEAL_ABSORB_TEST `+
	`MOD_CRIT_CHANCE_FOR_CASTER 309 MOD_CREATURE_AOE_DAMAGE_AVOIDANCE 311 312 313 PREVENT_RESURRECTION `+
	`UNDERWATER_WALKING PERIODIC_HASTE`, " ")

func EffectName(id uint32) string {
	if id == 0 {
		return ""
	}
	if int(id) < len(effectNames) {
		return effectNames[id]
	}
	return ""
}

func AuraName(id uint32) string {
	if id == 0 {
		return ""
	}
	if int(id) < len(auraNames) {
		return auraNames[id]
	}
	return ""
}

// Selected effect / aura IDs used by the importer.
const (
	EffectApplyAura          = 6
	EffectTriggerSpell       = 64
	EffectEnchantItem        = 53
	EffectEnchantItemTemp    = 54
	EffectEnchantPrismatic   = 156
	EffectApplyAreaAuraRaid  = 65
	EffectApplyAreaAuraParty = 35

	AuraDummy                = 4
	AuraModDamageDone        = 13
	AuraModResistance        = 22
	AuraModStat              = 29
	AuraModIncreaseHealth    = 34
	AuraModIncreaseEnergy    = 35
	AuraProcTriggerSpell     = 42
	AuraProcTriggerDamage    = 43
	AuraModPowerRegen        = 85
	AuraModAttackPower       = 99
	AuraAddFlatModifier      = 107
	AuraAddPctModifier       = 108
	AuraModTargetResistance  = 123
	AuraModRangedAttackPower = 124
	AuraModHealingDone       = 135
	AuraModShieldBlockValue  = 158
	AuraModRating            = 189
	AuraModExpertise         = 240
)
